### ISSUE TITLE
Unknown error after download(Error: 2 UNKNOWN)

### ISSUE THREAD

**Issue by kousuke** [firebase/quickstart-nodejs#60]
I did just download, and run, after then, I got this error.

```
Kousuke-mbp:Repos kousuke$ git clone git@github.com:firebase/quickstart-nodejs.git
Cloning into 'quickstart-nodejs'...
remote: Enumerating objects: 74, done.
remote: Counting objects: 100% (74/74), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 443 (delta 32), reused 48 (delta 17), pack-reused 369
Receiving objects: 100% (443/443), 211.01 KiB | 2.01 MiB/s, done.
Resolving deltas: 100% (224/224), done.
Kousuke-mbp:Repos kousuke$ cd quickstart-nodejs/firestore-emulator/javascript-quickstart/
Kousuke-mbp:javascript-quickstart kousuke$ npm install

> grpc@1.17.0 install /Users/kousuke/Repos/quickstart-nodejs/firestore-emulator/javascript-quickstart/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download 
[grpc] Success: "/Users/kousuke/Repos/quickstart-nodejs/firestore-emulator/javascript-quickstart/node_modules/grpc/src/node/extension_binary/node-v57-darwin-x64-unknown/grpc_node.node" is installed via remote
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN cloud-firestore-emulator-javascript-quickstart@1.0.1 No repository field.
npm WARN cloud-firestore-emulator-javascript-quickstart@1.0.1 No license field.

added 211 packages from 597 contributors and audited 461 packages in 6.737s
found 0 vulnerabilities

Kousuke-mbp:javascript-quickstart kousuke$ node -v
v8.12.0
Kousuke-mbp:javascript-quickstart kousuke$ firebase setup:emulators:firestore
i  firestore: downloading emulator...
Kousuke-mbp:javascript-quickstart kousuke$ firebase --version 
6.1.2
Kousuke-mbp:javascript-quickstart kousuke$ uname -a
Darwin Kousuke-mbp.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
Kousuke-mbp:javascript-quickstart kousuke$ firebase serve --only firestore
✔  firestore: started on http://localhost:8080
⚠  firestore: Feb 25, 2019 3:38:49 PM io.gapi.emulators.netty.NettyUtil applyJava7LongHostnameWorkaround
INFO: Unable to apply Java 7 long hostname workaround.

Dev App Server is now running.


API endpoint: http://localhost:8080

^Z
[1]+  Stopped                 firebase serve --only firestore
Kousuke-mbp:javascript-quickstart kousuke$ bg
[1]+ firebase serve --only firestore &
Kousuke-mbp:javascript-quickstart kousuke$ java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
Kousuke-mbp:javascript-quickstart kousuke$ npm test

> cloud-firestore-emulator-javascript-quickstart@1.0.1 test /Users/kousuke/Repos/quickstart-nodejs/firestore-emulator/javascript-quickstart
> FIREBASE_FIRESTORE_EMULATOR_ADDRESS='127.0.0.1:8080' mocha



(node:54347) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
⚠  firestore: Feb 25, 2019 3:39:16 PM io.gapi.emulators.grpc.GrpcServer$3 operationComplete
INFO: Adding handler(s) to newly registered Channel.

⚠  firestore: Feb 25, 2019 3:39:16 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected HTTP/2 connection.

  My app
⚠  firestore: Feb 25, 2019 3:39:16 PM com.google.cloud.datastore.emulator.impl.util.WrappedStreamObserver onError
INFO: operation failed: unimplemented

    1) "before each" hook for "require users to log in before creating a profile"

View rule coverage information at http://localhost:8080/emulator/v1/projects/firestore-emulator-example:ruleCoverage.html


  0 passing (487ms)
  1 failing

  1) "before each" hook for "require users to log in before creating a profile":
     Error: 2 UNKNOWN: 
      at Object.exports.createStatusError (node_modules/grpc/src/common.js:91:15)
      at Object.onReceiveStatus (node_modules/grpc/src/client_interceptors.js:1204:28)
      at InterceptingListener._callNext (node_modules/grpc/src/client_interceptors.js:568:42)
      at InterceptingListener.onReceiveStatus (node_modules/grpc/src/client_interceptors.js:618:8)
      at callback (node_modules/grpc/src/client_interceptors.js:845:24)



npm ERR! Test failed.  See above for more details.
```

**Comment by rb1econ** [comment]
getting this error as well 👍

**Comment by ryanpbrewster** [comment]
What version of the Firebase CLI tool are you using?
```
firebase --version
```

**Comment by ryanpbrewster** [comment]
Closing this issue out, I believe recent versions of the Firestore emulator have fixed this error.
