### ISSUE TITLE
UnsupportedClassVersionError

### ISSUE THREAD

**Issue by bijoutrouvaille** [firebase/quickstart-nodejs#68]
Running the emulator after `firebase setup:emulators:firestore` gives the following error:

```
firebase serve --only firestore                                                                
✔  firestore: started on http://localhost:8080
⚠  firestore: Exception in thread "main"
⚠  firestore: java.lang.UnsupportedClassVersionError: com/google/cloud/datastore/emulator/firestore/CloudFirestore : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
⚠  firestore:
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
⚠  firestore:
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
⚠  firestore:


Error: firestore: emulator has exited with code: 1
```

**Comment by samtstern** [comment]
@bijoutrouvaille I think this is a Java version compatibility issue.  Do you have Java 8 installed on your machine?  What do you get when you run `java -version`?

**Comment by samtstern** [comment]
cc @ryanpbrewster I am surprised the error is this ugly.

**Comment by bijoutrouvaille** [comment]
@samtstern You are right on both accounts. I had to update my JDK, which apparently is different from the system Java version. And the error is pretty bad. Not a Java guy. Thanks for the quick help. The emulator is running now.

**Comment by samtstern** [comment]
@bijoutrouvaille glad it worked!

**Comment by katowulf** [comment]
Reopening this to address the error message (not useful) and docs (incomplete). Ran into this today. Found that [our setup doc](https://firebase.google.com/docs/rules/emulator-setup) doesn't mention which Java dependency--JRE, JSE, JDK, MRE, WTF, or OMG--is needed (okay, I made some of those up). 

Furthermore, [download for 14](https://www.oracle.com/java/technologies/javase-jdk14-downloads.html) seems broken on the Java site, which exacerbates the issue.
![image](https://user-images.githubusercontent.com/959972/78458527-f8bb7d00-7666-11ea-8d3c-8cf93a64eed6.png)
